echo "// This file is autogenerated. Do not edit it.. (More importantly don't check it in..." > source/git.h
echo "const char* gitrel=\"$(git describe --tags --dirty)\";" >> source/git.h
echo "const char* gitrev=\"$(git rev-parse --short HEAD)\";" >> source/git.h


